import * as React from 'react';
import { Dispatch } from 'redux';
import { connect } from 'react-redux';

import Flag from '../presentational/Flag';

import { ResumeLanguage } from '../../models/language';
import { ResumeModel } from '../../models/resume';

import { changeLanguage } from '../../actions/language';

import { Language } from '../../constants/language';

import styled from 'styled-components';

export interface HeaderProps {
  username: string;
  language: ResumeLanguage;
  dispatch: Dispatch<{}>;
}

const HeaderHeight = '30px';

const HeaderContainer = styled.div`
  color: white;
  font-size: 14px;
  background: #666;
  text-align: left;
  height: ${HeaderHeight};
  padding-left: 5px;
  padding-right: 5px; 
  line-height: ${HeaderHeight};
`;
const Flags = styled.span`
  float: right;
`;

const Separator = styled.span`
  margin-left: 5px;
  margin-right: 5px;
`;

class Header extends React.PureComponent<HeaderProps> {
  handleLanguageChanged = (language: Language) => {
    const { dispatch } = this.props;
    dispatch(changeLanguage(language));
  }

  render () {
    const { handleLanguageChanged } = this;
    const { username } = this.props;
    return (
      <HeaderContainer>
        <span>{username}</span>
        <Separator>|</Separator>
        <span>Generated by TypeResume</span>

        <Flags>
          <Flag language={Language.Chinese} onClick={handleLanguageChanged}/>
          <Flag language={Language.English} onClick={handleLanguageChanged}/>
        </Flags>
      </HeaderContainer>
    );
  }
}

const mapStateToProps = (state: ResumeModel) => ({
  language: state.global.language,
  username: state.profile.username
});

export default connect(mapStateToProps)(Header);