import * as React from 'react';

import Flag from '../Flag';

export interface HeaderProps {
  username: string;
  onLanguageChanged?: (language: string) => void;
}

export default class Header extends React.PureComponent<HeaderProps> {
  handleLanguageChanged = (language: string) => {
    const { onLanguageChanged } = this.props;
    if (onLanguageChanged) {
      onLanguageChanged(language);
    }
  }

  render () {
    const { handleLanguageChanged } = this;
    const { username } = this.props;
    return (
      <div className="header">
        <span>{username}</span>
        <span>|</span>
        <span>Generated by TypeResume</span>

        <Flag language="Chinese" onClick={handleLanguageChanged}/>
        <Flag language="English" onClick={handleLanguageChanged}/>
      </div>
    );
  }
}